# Generated by Django 4.2.16 on 2024-11-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('timing', models.CharField(max_length=50)),
                ('today', models.BooleanField()),
            ],
        ),
    ]
