# Generated by Django 4.2.16 on 2024-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryApp', '0002_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydata',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
